### ISSUE TITLE
glmmTMB support?

### ISSUE THREAD

**Issue by pitakakariki** [pitakakariki/simr#75]
Tricky bits probably:

 * `simulate` with modified parameter values
 * `use.u` in `simulate`

**Comment by RmeanyMAN** [comment]
Hi, is there support for glmmTMB and powerSim() and powerCurve() at this point in time? Thanks!

**Comment by pitakakariki** [comment]
No support yet, but I've had another look and it might not be as hard as I thought. I'm unlikely to find the time for a while though.

**Comment by pitakakariki** [comment]
`simulate.glmmTMB` lives in `methods.R`.

    object$obj$simulate(par = object$fit$parfull)$yobs

That goes back to `TMB` I think, but `doSim` should be able to pass modified parameters.

**Comment by rosemckeon** [comment]
Hi @pitakakariki - wondering if you'd had chance to look at including this yet, or if you know of another method for glmmTMB?

**Comment by pitakakariki** [comment]
Not much progress on this unfortunately. Simplest way to do it might be to tweak your glmmTMB model by hand (i.e. edit the values in `x$fit$parfull`) and write functions to pass to `fit` and `test`.

**Comment by rosemckeon** [comment]
ok, thanks @pitakakariki - maybe I'll take a peek at that.

**Comment by bbolker** [comment]
I'd be willing to help push this forward if you like.  We really should add `newparams` and `newdata` to `simulate.glmmTMB` ...

**Comment by pitakakariki** [comment]
If `newparams` and `newdata` are added to `simulate.glmmTMB` that's most of the work done I reckon. That might finally encourage me to add the appropriate connectors at this end.

**Comment by bbolker** [comment]
Actually, these are there already!  There are some outstanding issues (https://github.com/glmmTMB/glmmTMB/issues/953) but you could give it a spin and see how it goes ...

**Comment by atejon123** [comment]
I wanted to ask, what is the current situation of using simr with glmmTMB?

I am using this model:
`model <- glmmTMB(area_proj_strength ~ group + (1|brain), family = lognormal(link = "log"),ziformula = ~ group + (1 | brain), data = data, dispformula = ~ group+ (1|brain))`

and I tried using simr::powerCurve with extend() function to simulate the power of different sample sizes. It ran without errors, but then I came across [#1162](https://github.com/glmmTMB/glmmTMB/issues/1162), which made me think that simr may not be correctly interpreting models with ziformula and dispformula components, and instead I should be using simulate() function. 

Could anyone advise on this? If the simr runs without errors, does it mean that its previous incompatibilities with glmmTMB have been resolved, or is there still a chance that certain parts of the model are not interpreted correctly?

**Comment by bbolker** [comment]
Good question, I don't know. FWIW the issues discussed [here](https://github.com/glmmTMB/glmmTMB/issues/953) are probably not relevant for your usage `simr`. (There are some deep questions/rabbit holes about whether you are using "old-style" or "new-style" random effects *sensu* Hodges and Clayton, but in this case you clearly want to be picking new random-effects values *unconditionally*.) 


Hodges, James S., and Murray K. Clayton. “Random Eﬀects Old and New.” 2011. https://www.researchgate.net/profile/Suhail-Doi/post/Is-the-random-effects-estimator-worse-than-the-fixed-effect-estimator-under-heterogeneity/attachment/59d6330879197b8077990bab/AS%3A372836079292416%401465902456174/download/Hodges.pdf.

**Comment by pitakakariki** [comment]
@atejon123 `glmmTMB` is still not supported. I'm surprised it ran without errors. Treat any results with caution!
